# famous_persons = ['john Fruschianto', 'Billy Idol', 'Antony Kidis', 'Elton John']
# famous_persons.sort()
# print(famous_persons)
# famous_persons.sort(reverse=True)
# print(famous_persons)
# sorted(famous_persons)
# print(famous_persons)
# print(sorted(famous_persons, reverse=True))

countries = ['USA', 'Canada', 'Russia', 'France', 'United Kingdom']
print(countries)
print(sorted(countries))
print(countries)
print(sorted(countries,reverse=True))
countries.reverse()
print(countries)
countries.sort()
print(countries)
countries.sort(reverse=True)
print(countries)